import { Inter } from "next/font/google";
import NavBar from "../ui/NavBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <div><NavBar /></div>
      <div className={inter.className}>
        {children}
      </div>
    </>
  );
}
